---
- name: Create the /var/cyhy/code-gov-update directory
  ansible.builtin.file:
    group: "{{ code_gov_update_file_owner_group | default(omit) }}"
    mode: u=rwx,g=rx,o=rx
    owner: "{{ code_gov_update_file_owner_username | default(omit) }}"
    path: /var/cyhy/code-gov-update
    state: directory

- name: Install the Docker Compose configuration
  ansible.builtin.template:
    dest: /var/cyhy/code-gov-update/compose.yml
    group: "{{ code_gov_update_file_owner_group | default(omit) }}"
    mode: u=rw,g=r,o=r
    owner: "{{ code_gov_update_file_owner_username | default(omit) }}"
    src: compose.yml.j2
