---
- name: Create the /var/cyhy/code-gov-update directory
  ansible.builtin.file:
    mode: 0755
    path: /var/cyhy/code-gov-update
    state: directory

- name: Download and untar the code-gov-update tarball
  ansible.builtin.unarchive:
    dest: /var/cyhy/code-gov-update
    extra_opts:
      - "--strip-components=1"
    remote_src: yes
    src: https://api.github.com/repos/cisagov/code-gov-update/tarball/develop
