---
# tasks file for code_gov_update
- name: Create the /var/cyhy/code-gov-update directory
  file:
    path: /var/cyhy/code-gov-update
    state: directory
    mode: 0755

- name: Download and untar the code-gov-update tarball
  unarchive:
    src: https://api.github.com/repos/cisagov/code-gov-update/tarball/develop
    dest: /var/cyhy/code-gov-update
    remote_src: yes
    extra_opts:
      - "--strip-components=1"
