---
- name: Create the /var/cyhy/code-gov-update directory
  file:
    mode: 0755
    path: /var/cyhy/code-gov-update
    state: directory

- name: Download and untar the code-gov-update tarball
  # ansible-lint E208 gives an error if we don't specify the mode,
  # but we definitely don't want to do that here since it will
  # override the permissions on the files in the archive.
  unarchive: # noqa 208
    dest: /var/cyhy/code-gov-update
    extra_opts:
      - "--strip-components=1"
    remote_src: yes
    src: https://api.github.com/repos/cisagov/code-gov-update/tarball/develop
