---
- name: Create the /var/cyhy/code-gov-update directory
  ansible.builtin.file:
    mode: 0755
    path: /var/cyhy/code-gov-update
    state: directory

- name: Install the Docker Compose configuration
  ansible.builtin.copy:
    dest: /var/cyhy/code-gov-update
    mode: 0644
    src: docker-compose.yml
