---
version: "3.2"

secrets:
  aws_config:
    file: secrets/aws_config
  scraper_config:
    file: secrets/scraper.json

services:
  update:
    command:
      - "--cc=cisa-cyhy-mailer@gwe.cisa.dhs.gov"
      - "--from=code@cyber.dhs.gov"
      - "--html=body.html"
      - "--json=code.json"
      - "--log-level=info"
      - "--reply=cisa-cyhy-mailer@gwe.cisa.dhs.gov"
      - "--subject=\"Latest code.gov JSON file\""
      - "--text=body.txt"
      - "--to=webpublishing@hq.dhs.gov"
    environment:
      - AWS_CONFIG_FILE=/run/secrets/aws_config
      - AWS_PROFILE=default
    image: cisagov/code-gov-update:0.2.0
    secrets:
      - source: aws_config
        target: aws_config
      - source: scraper_config
        target: scraper_config.json
